# https://kitian616.github.io/jekyll-TeXt-theme/docs/en/quick-start

# Site general settings
title: Squadra di Matematica del Kope
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Sito ufficiale della squadra di matematica del Liceo "N. Copernico" di Prato
baseurl: # "/Squadra-di-Matematica-del-Kope"
url: "https://kevinmaggi.github.io"

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-compose

# Theme settings
theme: minimal-mistakes-jekyll


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


include: ["_pages"]

# ---------------
# Minimal Mistakes theme configuration
# ---------------

# Skin
minimal_mistakes_skin: "default"

# Language and timezone
locale: "it-IT"
timezone: Europe/Rome

# General info
# title: "Kevin Maggi" # Specified above in Jekyll configurations
title_separator: "|"
#subtitle: ""
name: "Squadra di Matematica del Kope"
repository: "KevinMaggi/Squadra-di-Matematica-del-Kope"